version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}_nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: dev
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/var/www/html:ro,cached
      depends_on:
        - laravel

    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}_laravel:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: 1000
          HOST_GID: 1000
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}_laravel
      volumes:
        - .:/var/www/html:cached
      depends_on:
        - mysql

    ### Cron tasks, will add later if needed
#    supervisord:
#      <<: *laravel-template
#      container_name: ${COMPOSE_PROJECT_NAME}_supervisord
#      expose: []
#      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: souzokuhiyou
      ports:
        - "33061:3306"
      volumes:
        - ./storage/mysql-data:/var/lib/mysql:delegated
